export const items = [
  {
    "id": "F003-2024",
    "title": "Whitney Biennial",
    "fullTitle": "Whitney Biennial",
    "category": "Arte e architettura",
    "kind": "Grafica di edizione",
    "year": 2024,
    "src": "assets/curated-3.png",
    "width": 3307,
    "height": 1894,
    "background": "#ff951e",
    "note": "Il nome della biennale occupa quasi tutta la superficie, su un gradiente arancio e azzurro. La tipografia diventa il principale elemento di riconoscimento.",
    "source": "https://whitney.org/education/schools-educators/K-12/teaching-materials/teacher-guides/biennial2024",
    "credit": "Provenienza: whitney.org",
    "gallery": []
  },
  {
    "id": "dekmantel-affissione",
    "title": "Dekmantel Festival",
    "fullTitle": "Dekmantel Festival — Affissione urbana",
    "category": "Musica e spettacolo",
    "kind": "Applicazione",
    "year": 2024,
    "src": "assets/dekmantel-affissione.jpg",
    "width": 1440,
    "height": 1800,
    "background": "#202020",
    "note": "Una colonna per affissioni porta colori, forme e marchi del festival nello spazio urbano. Il supporto curvo cambia la lettura del manifesto e trasforma l’identità in una presenza nella città.",
    "source": "https://dekmantel.com/editorial/rewind-2024-between-fiction-and-nature",
    "credit": "Identità: Jonathan Castro Alejos. Crediti fotografici della pagina: Bianca Paul, Ted Grindei & Evi Cats.",
    "gallery": [
      {
        "src": "assets/dekmantel-affissione.jpg",
        "label": "Applicazione"
      },
      {
        "src": "assets/dekmantel-manifesto.jpg",
        "label": "Manifesto"
      },
      {
        "src": "assets/curated-73.png",
        "label": "Marchio"
      }
    ],
    "context": "Nell’intervista pubblicata da Dekmantel, Jonathan Castro collega l’identità ai ponti dell’Amsterdamse Bos e ai manifesti Chicha di Lima. Il sistema viene declinato tra immagini digitali e grandi affissioni urbane."
  },
  {
    "id": "F036-2025",
    "title": "AGI Open",
    "fullTitle": "AGI Open",
    "category": "Design e tipografia",
    "kind": "Manifesto",
    "year": 2025,
    "src": "assets/curated-36.png",
    "width": 720,
    "height": 1019,
    "background": "#000000",
    "note": "Due forme geometriche e una tipografia essenziale costruiscono la gerarchia. Città e date rendono il manifesto specifico per l’edizione di Ho Chi Minh City.",
    "source": "https://www.ticketmelon.com/rice/agi-open",
    "credit": "Provenienza: www.ticketmelon.com",
    "gallery": []
  },
  {
    "id": "F020-formato",
    "title": "Berlinale",
    "fullTitle": "Berlinale",
    "category": "Cinema",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-20.png",
    "width": 1200,
    "height": 675,
    "background": "#f5f3ef",
    "note": "Il marchio identifica il formato del festival. È un punto di partenza per confrontare il segno ricorrente con i materiali delle singole edizioni.",
    "source": "https://www.kubinaut.de/de/projektmachende/profile/institutionen-finden/internationale-filmfestspiele-berlin/",
    "credit": "Provenienza: www.kubinaut.de",
    "gallery": []
  },
  {
    "id": "F037-2023",
    "title": "Biennale di Chaumont",
    "fullTitle": "Biennale internationale de design graphique de Chaumont",
    "category": "Design e tipografia",
    "kind": "Manifesto",
    "year": 2023,
    "src": "assets/curated-37.jpg",
    "width": 822,
    "height": 1174,
    "background": "#fae7e9",
    "note": "Lettere inclinate, forme tridimensionali e pattern convivono in un manifesto molto denso. Il nome della biennale attraversa l’immagine invece di occupare un blocco separato.",
    "source": "https://voyage.aprr.fr/autoroute-info/debut-de-la-4e-biennale-internationale-de-design-graphique-chaumont",
    "credit": "Provenienza: voyage.aprr.fr",
    "gallery": []
  },
  {
    "id": "F039-2025",
    "title": "Expo Osaka",
    "fullTitle": "Esposizioni universali",
    "category": "Esposizioni e fiere",
    "kind": "Marchio",
    "year": 2025,
    "src": "assets/curated-39.png",
    "width": 2000,
    "height": 1252,
    "background": "#f5f3ef",
    "note": "Il marchio dell’edizione permette di riconoscere una specifica occorrenza dell’esposizione. Nella lettura dell’archivio, anno e formato vanno tenuti distinti.",
    "source": "https://www.city.kyotango.lg.jp/top/soshiki/shokokanko/shokoshinko/4/expo2025/index.html",
    "credit": "Provenienza: www.city.kyotango.lg.jp",
    "gallery": []
  },
  {
    "id": "F018-2025",
    "title": "Quadriennale di Roma",
    "fullTitle": "Quadriennale di Roma",
    "category": "Arte e architettura",
    "kind": "Marchio",
    "year": 2025,
    "src": "assets/curated-18.webp",
    "width": 1799,
    "height": 1012,
    "background": "#f5f3ef",
    "note": "Il numero 18 è integrato nel segno nero, accanto al nome della Quadriennale. La numerazione entra nella forma stessa dell’identità di edizione.",
    "source": "https://www.finestresullarte.info/attualita/quadriennale-di-roma-2025-fantastica-18ma-edizione-presentazione",
    "credit": "Provenienza: www.finestresullarte.info",
    "gallery": []
  },
  {
    "id": "F094-2023",
    "title": "ATypI Paris",
    "fullTitle": "ATypI Conference",
    "category": "Design e tipografia",
    "kind": "Manifesto",
    "year": 2023,
    "src": "assets/curated-94.webp",
    "width": 1759,
    "height": 1173,
    "background": "#000000",
    "note": "Le parole e l’anno sono composti con lettere espanse e tagli netti, distribuiti su fasce di colore. Il piccolo blocco informativo completa la composizione.",
    "source": "https://hmctartcenter.org/articles/atypi-paris-2023-review",
    "credit": "Provenienza: hmctartcenter.org",
    "gallery": []
  },
  {
    "id": "F049-formato",
    "title": "Dutch Design Week",
    "fullTitle": "Dutch Design Week",
    "category": "Design e tipografia",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-49.png",
    "width": 2084,
    "height": 2085,
    "background": "#f5f3ef",
    "note": "Un segno del formato viene osservato come elemento di continuità. Il confronto con manifesti e campagne di edizione permette di capire quali parti del sistema cambiano.",
    "source": "https://www.worlddesignweeks.org/members/dutch-design-week",
    "credit": "Provenienza: www.worlddesignweeks.org",
    "gallery": []
  },
  {
    "id": "F041-2022",
    "title": "Triennale Milano",
    "fullTitle": "Esposizione Internazionale della Triennale di Milano",
    "category": "Esposizioni e fiere",
    "kind": "Grafica di edizione",
    "year": 2022,
    "src": "assets/curated-41.webp",
    "width": 1920,
    "height": 1280,
    "background": "#000000",
    "note": "Il titolo Unknown Unknowns si sovrappone a due volumi iridescenti su fondo nero. Le informazioni dell’edizione occupano il margine inferiore della composizione.",
    "source": "https://www.koozarch.com/essays/unknown-unknowns-an-introduction-to-mysteries",
    "credit": "Provenienza: www.koozarch.com",
    "gallery": []
  },
  {
    "id": "F076-2024",
    "title": "America’s Cup",
    "fullTitle": "America's Cup",
    "category": "Sport",
    "kind": "Marchio",
    "year": 2024,
    "src": "assets/curated-76.jpg",
    "width": 2000,
    "height": 1125,
    "background": "#f5f3ef",
    "note": "Il marchio lega il nome della competizione alla sua edizione. La scheda distingue il riconoscimento del formato dalla specificità di un singolo evento.",
    "source": "https://www.americascup.com/news/1622_37TH-AMERICA-S-CUP-REVEAL-AC37-LOGO",
    "credit": "Provenienza: www.americascup.com",
    "gallery": []
  },
  {
    "id": "F050-formato",
    "title": "London Design Festival",
    "fullTitle": "London Design Festival",
    "category": "Design e tipografia",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-50.png",
    "width": 400,
    "height": 583,
    "background": "#f5f3ef",
    "note": "Il segno ricorrente del festival costituisce una base per la lettura delle sue applicazioni. La sua presenza non esaurisce l’intero sistema visivo dell’evento.",
    "source": "https://www.somersethouse.org.uk/whats-on/sun-my-heart-marjan-van-aubel-studio",
    "credit": "Provenienza: www.somersethouse.org.uk",
    "gallery": []
  },
  {
    "id": "F035-formato",
    "title": "OFFF Barcelona",
    "fullTitle": "OFFF Barcelona",
    "category": "Design e tipografia",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-35.png",
    "width": 8425,
    "height": 2750,
    "background": "#f5f3ef",
    "note": "Il nome del festival viene trattato come segno identificativo. Manifesti, motion e materiali di edizione possono essere confrontati con questo elemento ricorrente.",
    "source": "https://www.offf.barcelona/",
    "credit": "Provenienza: www.offf.barcelona",
    "gallery": []
  },
  {
    "id": "dekmantel-manifesto",
    "title": "Dekmantel Festival",
    "fullTitle": "Dekmantel Festival — Manifesto 2024",
    "category": "Musica e spettacolo",
    "kind": "Manifesto",
    "year": 2024,
    "src": "assets/dekmantel-manifesto.jpg",
    "width": 1440,
    "height": 1800,
    "background": "#202020",
    "note": "Forme irregolari, colori accesi e una fascia di segni costruiscono una composizione verticale. Il confronto con il marchio e l’affissione mostra il passaggio dal segno al sistema visivo.",
    "source": "https://dekmantel.com/editorial/rewind-2024-between-fiction-and-nature",
    "credit": "Identità: Jonathan Castro Alejos. Crediti fotografici della pagina: Bianca Paul, Ted Grindei & Evi Cats.",
    "gallery": [
      {
        "src": "assets/dekmantel-affissione.jpg",
        "label": "Applicazione"
      },
      {
        "src": "assets/dekmantel-manifesto.jpg",
        "label": "Manifesto"
      },
      {
        "src": "assets/curated-73.png",
        "label": "Marchio"
      }
    ],
    "context": "Nell’intervista pubblicata da Dekmantel, Jonathan Castro collega l’identità ai ponti dell’Amsterdamse Bos e ai manifesti Chicha di Lima. Il sistema viene declinato tra immagini digitali e grandi affissioni urbane."
  },
  {
    "id": "F040-1920",
    "title": "Fiera Campionaria di Milano",
    "fullTitle": "Fiera Campionaria di Milano",
    "category": "Esposizioni e fiere",
    "kind": "Manifesto",
    "year": 1920,
    "src": "assets/curated-40.webp",
    "width": 1440,
    "height": 1060,
    "background": "#927a9b",
    "note": "L’immagine accosta un manifesto illustrato e la copertina del catalogo del 1920. Due supporti diversi permettono di osservare la comunicazione della stessa edizione.",
    "source": "https://www.salonemilano.it/en/articles/adi-fiera-milano-made-italy",
    "credit": "Provenienza: www.salonemilano.it",
    "gallery": []
  },
  {
    "id": "F063-2025",
    "title": "Festival di Sanremo",
    "fullTitle": "Festival di Sanremo",
    "category": "Musica e spettacolo",
    "kind": "Marchio",
    "year": 2025,
    "src": "assets/curated-63.png",
    "width": 1500,
    "height": 1000,
    "background": "#f5f3ef",
    "note": "Un marchio riferito a un’edizione del festival. È un documento da leggere insieme alle applicazioni della comunicazione e alla presenza del formato nel tempo.",
    "source": "https://www.siae.it/it/notizie/casasiae-sanremo75/",
    "credit": "Provenienza: www.siae.it",
    "gallery": []
  },
  {
    "id": "F101-2024",
    "title": "Adobe MAX",
    "fullTitle": "Adobe MAX",
    "category": "Congressi",
    "kind": "Grafica di edizione",
    "year": 2024,
    "src": "assets/curated-101.jpg",
    "width": 1200,
    "height": 526,
    "background": "#ef6600",
    "note": "Il nome MAX emerge in bianco su forme geometriche, texture e colori saturi. Il segno e lo sfondo lavorano insieme, anziché presentarsi come elementi isolati.",
    "source": "https://blog.adobe.com/en/publish/2024/10/04/max-gets-bold-new-visual-identity",
    "credit": "Provenienza: blog.adobe.com",
    "gallery": []
  },
  {
    "id": "F033-2025",
    "title": "Chemnitz 2025",
    "fullTitle": "Capitale europea della cultura",
    "category": "Cultura",
    "kind": "Marchio",
    "year": 2025,
    "src": "assets/curated-33.png",
    "width": 1182,
    "height": 1064,
    "background": "#f5f3ef",
    "note": "Il marchio identifica Chemnitz come Capitale europea della cultura nel 2025. Il nome della città e l’anno circoscrivono il progetto a una specifica edizione.",
    "source": "https://chemnitz2025.de/en/use-our-logo/",
    "credit": "Provenienza: chemnitz2025.de",
    "gallery": []
  },
  {
    "id": "F054-2025",
    "title": "D&AD Festival",
    "fullTitle": "D&AD Festival",
    "category": "Design e tipografia",
    "kind": "Grafica di edizione",
    "year": 2025,
    "src": "assets/curated-54.jpg",
    "width": 1600,
    "height": 1067,
    "background": "#332f3d",
    "note": "La ripetizione di D&AD Festival 2025 forma un pattern intorno al segno centrale. L’identità è visibile sia come marchio sia come trattamento della superficie.",
    "source": "https://www.creativebloq.com/professional-development/creative-careers/the-only-thing-thats-guaranteed-is-change-d-and-ads-president-shares-his-advice-for-young-creatives",
    "credit": "Provenienza: www.creativebloq.com",
    "gallery": []
  },
  {
    "id": "F077-formato",
    "title": "Giochi Olimpici",
    "fullTitle": "Giochi Olimpici",
    "category": "Sport",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-77.png",
    "width": 1300,
    "height": 600,
    "background": "#f5f3ef",
    "note": "Il simbolo dei cinque anelli viene osservato come segno del formato. Le identità delle singole edizioni costituiscono un livello diverso del sistema.",
    "source": "https://olympic.kz/en/page/mok",
    "credit": "Provenienza: olympic.kz",
    "gallery": []
  },
  {
    "id": "F073-2024",
    "title": "Dekmantel Festival",
    "fullTitle": "Dekmantel Festival",
    "category": "Musica e spettacolo",
    "kind": "Marchio",
    "year": 2024,
    "src": "assets/curated-73.png",
    "width": 1440,
    "height": 703,
    "background": "#f5f3ef",
    "note": "Un segno deformato e compatto dell’identità 2024. Il confronto con il manifesto e l’affissione presenti nell’archivio mostra come il segno entra in una composizione più ampia.",
    "source": "https://dekmantel.com/editorial/dekmantel-festival-2024",
    "credit": "Provenienza: dekmantel.com",
    "gallery": [
      {
        "src": "assets/dekmantel-affissione.jpg",
        "label": "Applicazione"
      },
      {
        "src": "assets/dekmantel-manifesto.jpg",
        "label": "Manifesto"
      },
      {
        "src": "assets/curated-73.png",
        "label": "Marchio"
      }
    ],
    "context": "Marchio, manifesto e fotografia di un’affissione documentano tre livelli della stessa identità. La scheda li affianca per osservare il passaggio dal segno alla sua applicazione."
  },
  {
    "id": "F051-2024",
    "title": "World Design Capital",
    "fullTitle": "World Design Capital",
    "category": "Design e tipografia",
    "kind": "Marchio",
    "year": 2024,
    "src": "assets/curated-51.webp",
    "width": 2500,
    "height": 2500,
    "background": "#f5f3ef",
    "note": "Il documento si riferisce al 2024, collegando un formato internazionale a una sua edizione. Il contesto di edizione evita di leggere il marchio come un segno senza tempo.",
    "source": "https://www.lajollahistory.org/current-and-upcoming",
    "credit": "Provenienza: www.lajollahistory.org",
    "gallery": []
  },
  {
    "id": "F034-2025",
    "title": "Agrigento 2025",
    "fullTitle": "Capitale italiana della cultura",
    "category": "Cultura",
    "kind": "Marchio",
    "year": 2025,
    "src": "assets/curated-34.jpg",
    "width": 2048,
    "height": 1152,
    "background": "#f5f3ef",
    "note": "Il marchio collega Agrigento al titolo di Capitale italiana della cultura 2025. È un esempio di identità che si riferisce insieme a un luogo e a un anno.",
    "source": "https://www.raiplay.it/programmi/agrigentocapitaledellacultura2025",
    "credit": "Provenienza: www.raiplay.it",
    "gallery": []
  },
  {
    "id": "F052-formato",
    "title": "Brand New Conference",
    "fullTitle": "Brand New Conference",
    "category": "Design e tipografia",
    "kind": "Marchio",
    "year": null,
    "src": "assets/curated-52.png",
    "width": 180,
    "height": 180,
    "background": "#f5f3ef",
    "note": "Il segno identifica la conferenza nel materiale raccolto. Le applicazioni delle diverse edizioni possono essere confrontate per osservare continuità e variazioni.",
    "source": "https://www.underconsideration.com/brandnewconference/",
    "credit": "Provenienza: www.underconsideration.com",
    "gallery": []
  }
];
